# Generated by Django 5.0.6 on 2024-09-19 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(default=0, verbose_name='Codigo Depto')),
                ('nombre', models.CharField(max_length=30, verbose_name='Departamento')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='PaisRepatriacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, verbose_name='Pais')),
            ],
            options={
                'verbose_name': 'Pais Repatriación',
                'verbose_name_plural': 'Pais Repatriación',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(default=0, verbose_name='Codigo Mpio')),
                ('nombre', models.CharField(max_length=30, verbose_name='Municipio')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='departamento.departamento')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
    ]
