# Generated by Django 5.0.6 on 2025-03-12 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asociado', '0001_initial'),
        ('parametro', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialPagos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaPago', models.DateField(blank=True, null=True, verbose_name='Fecha Pago')),
                ('valorPago', models.IntegerField(verbose_name='Valor Pago')),
                ('diferencia', models.IntegerField(blank=True, null=True, verbose_name='Diferencia')),
                ('estadoRegistro', models.BooleanField(verbose_name='Estado')),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaModificacion', models.DateTimeField(auto_now=True)),
                ('asociado', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='asociado.asociado')),
                ('formaPago', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='parametro.formapago')),
                ('mesPago', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='parametro.mestarifa')),
                ('userCreacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_creacion', to=settings.AUTH_USER_MODEL)),
                ('userModificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_modificacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Pagos',
                'verbose_name_plural': 'Historial de Pagos',
                'ordering': ['pk'],
            },
        ),
    ]
