# Generated by Django 5.0.6 on 2024-09-19 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asociado', '0001_initial'),
        ('parametro', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialPagos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('valorPago', models.IntegerField(verbose_name='Valor Pago')),
                ('diferencia', models.IntegerField(blank=True, null=True, verbose_name='Diferencia')),
                ('estadoRegistro', models.BooleanField(verbose_name='Estado')),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaModificacion', models.DateTimeField(auto_now=True)),
                ('asociado', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='asociado.asociado')),
                ('formaPago', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='parametro.formapago')),
                ('mesPago', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='parametro.mestarifa')),
            ],
            options={
                'verbose_name': 'Historial de Pagos',
                'verbose_name_plural': 'Historial de Pagos',
                'ordering': ['pk'],
            },
        ),
    ]
