# Generated by Django 5.0.6 on 2025-03-12 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parametro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asociado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre1', models.CharField(blank=True, max_length=30, null=True, verbose_name='Primer Nombre')),
                ('nombre2', models.CharField(blank=True, max_length=30, null=True, verbose_name='Segundo Nombre')),
                ('apellido1', models.CharField(blank=True, max_length=30, null=True, verbose_name='Primer Apellido')),
                ('apellido2', models.CharField(blank=True, max_length=30, null=True, verbose_name='Segundo Apellido')),
                ('tipoDocumento', models.CharField(choices=[('CC', 'CEDULA'), ('RC', 'REGISTRO CIVIL'), ('TI', 'TARJETA IDENTIDAD'), ('CE', 'CEDULA EXTRANJERA'), ('PA', 'PASAPORTE'), ('PPT', 'PERMISO PROTECCION TEMPORAL'), ('SD', 'SIN DOCUMENTO')], default='RC', verbose_name='Tipo Documento')),
                ('numDocumento', models.CharField(max_length=10, verbose_name='Número Documento')),
                ('numCelular', models.CharField(max_length=11, verbose_name='Numero Celular')),
                ('hogarinfantil', models.CharField(choices=[('SARDINITOS', 'SARDINITOS'), ('JESUS OBRERO', 'JESUS OBRERO')], default='SARDINITOS', verbose_name='HogarInfantil')),
                ('estadoAsociado', models.CharField(choices=[('ACTIVO', 'ACTIVO'), ('RETIRO', 'RETIRO')], default='ACTIVO', verbose_name='Estado Asociado')),
                ('desplazado', models.BooleanField(default=False, verbose_name='Desplazado')),
                ('estadoRegistro', models.BooleanField(verbose_name='Estado')),
                ('fechaIngreso', models.DateField(blank=True, null=True, verbose_name='Fecha Ingreso')),
                ('fechaRetiro', models.DateField(blank=True, null=True, verbose_name='Fecha Retiro')),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaModificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Asociado',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='TarifaAsociado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cuota', models.IntegerField(verbose_name='Aporte')),
                ('estadoRegistro', models.BooleanField(verbose_name='Estado')),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaModificacion', models.DateTimeField(auto_now=True)),
                ('asociado', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='asociado.asociado')),
            ],
            options={
                'verbose_name': 'Tarifa Por Asociado',
                'verbose_name_plural': 'Tarifa Por Asociado',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='ParametroAsociado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estadoRegistro', models.BooleanField(verbose_name='Estado')),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaModificacion', models.DateTimeField(auto_now=True)),
                ('asociado', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='asociado.asociado')),
                ('primerMes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='parametro.mestarifa')),
                ('tarifaAsociado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='asociado.tarifaasociado')),
            ],
            options={
                'verbose_name': 'Parametros Asociado',
                'ordering': ['pk'],
            },
        ),
    ]
