# Generated by Django 5.0.6 on 2024-09-19 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parametro', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asociado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=30, verbose_name='Apellido')),
                ('tipoDocumento', models.CharField(choices=[('CEDULA', 'CEDULA'), ('REGISTRO CIVIL', 'REGISTRO CIVIL'), ('TARJETA IDENTIDAD', 'TARJETA IDENTIDAD'), ('CEDULA EXTRANJERA', 'CEDULA EXTRANJERA'), ('PASAPORTE', 'PASAPORTE')], default='CEDULA', verbose_name='Tipo Documento')),
                ('numDocumento', models.CharField(max_length=10, verbose_name='Número Documento')),
                ('numCelular', models.CharField(max_length=11, verbose_name='Numero Celular')),
                ('hogarinfantil', models.CharField(choices=[('ANGELITOS', 'ANGELITOS'), ('CELMIRA MEJIA', 'CELMIRA MEJIA'), ('ISABELA', 'ISABELA'), ('NIÑO DE PRAGA', 'NIÑO DE PRAGA'), ('SANTANDER', 'SANTANDER')], default='ANGELITOS', verbose_name='HogarInfantil')),
                ('estadoRegistro', models.BooleanField(verbose_name='Estado')),
                ('fechaIngreso', models.DateField(verbose_name='Fecha Ingreso')),
                ('fechaRetiro', models.DateField(blank=True, null=True, verbose_name='Fecha Retiro')),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaModificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Asociado',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='TarifaAsociado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cuota', models.IntegerField(verbose_name='Aporte')),
                ('estadoRegistro', models.BooleanField(verbose_name='Estado')),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaModificacion', models.DateTimeField(auto_now=True)),
                ('asociado', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='asociado.asociado')),
            ],
            options={
                'verbose_name': 'Tarifa Por Asociado',
                'verbose_name_plural': 'Tarifa Por Asociado',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='ParametroAsociado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estadoRegistro', models.BooleanField(verbose_name='Estado')),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaModificacion', models.DateTimeField(auto_now=True)),
                ('asociado', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='asociado.asociado')),
                ('primerMes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='parametro.mestarifa')),
                ('tarifaAsociado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='asociado.tarifaasociado')),
            ],
            options={
                'verbose_name': 'Parametros Asociado',
                'ordering': ['pk'],
            },
        ),
    ]
