# Generated by Django 5.0.6 on 2024-09-20 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociado', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asociado',
            name='estadoAsociado',
            field=models.CharField(choices=[('ACTIVO', 'ACTIVO'), ('INACTIVO', 'INACTIVO'), ('RETIRADO', 'RETIRADO')], default='ACTIVO', verbose_name='Estado Asociado'),
        ),
    ]
