# Generated by Django 5.0.6 on 2025-06-09 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociado', '0002_alter_asociado_numdocumento'),
    ]

    operations = [
        migrations.AddField(
            model_name='asociado',
            name='nombreAcudiente',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre Acudiente'),
        ),
        migrations.AddField(
            model_name='asociado',
            name='numDocAcudiente',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Número Documento Acudiente'),
        ),
    ]
