# Generated by Django 5.0.6 on 2024-09-20 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociado', '0002_asociado_estadoasociado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asociado',
            name='estadoAsociado',
            field=models.CharField(choices=[('ACTIVO', 'ACTIVO'), ('INACTIVO', 'INACTIVO'), ('RETIRO', 'RETIRO')], default='ACTIVO', verbose_name='Estado Asociado'),
        ),
    ]
