# Generated by Django 5.0.6 on 2024-09-20 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociado', '0003_alter_asociado_estadoasociado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asociado',
            name='estadoAsociado',
            field=models.CharField(choices=[('ACTIVO', 'ACTIVO'), ('RETIRO', 'RETIRO')], default='ACTIVO', verbose_name='Estado Asociado'),
        ),
        migrations.AlterField(
            model_name='asociado',
            name='fechaIngreso',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Ingreso'),
        ),
    ]
