# Generated by Django 5.0.6 on 2025-06-10 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociado', '0004_asociado_tipodocacudiente'),
    ]

    operations = [
        migrations.AddField(
            model_name='asociado',
            name='ciudadResidencia',
            field=models.CharField(blank=True, null=True, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='asociado',
            name='direccion',
            field=models.CharField(blank=True, null=True, verbose_name='Dirección'),
        ),
    ]
