# Generated by Django 5.0.6 on 2024-09-23 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociado', '0004_alter_asociado_estadoasociado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asociado',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='asociado',
            name='nombre',
        ),
        migrations.AddField(
            model_name='asociado',
            name='apellido1',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Primer Apellido'),
        ),
        migrations.AddField(
            model_name='asociado',
            name='apellido2',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Segundo Apellido'),
        ),
        migrations.AddField(
            model_name='asociado',
            name='nombre1',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Primer Nombre'),
        ),
        migrations.AddField(
            model_name='asociado',
            name='nombre2',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Segundo Nombre'),
        ),
    ]
